{% set name = "rfpimp" %}
{% set version = "1.3.5" %}
{% set sha256 = "8c373c3ee41880a7f516b5a7814230c7c02fee2b877b5f70e1648c443d5a0fde" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pandas
    - scikit-learn
    - matplotlib

test:
  imports:
    - rfpimp

about:
  home: https://github.com/parrt/random-forest-importances
  license: MIT
  license_family: MIT
  summary: Code to compute permutation and drop-column importances in Python scikit-learn random forests

extra:
  recipe-maintainers:
    - ericmjl
