{% set name = "rfpimp" %}
{% set version = "1.3.2" %}
{% set sha256 = "30ac120edacda616db6c3b1d2d2556c6a3c771643ab45d489da201c53ae97a91" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pandas
    - scikit-learn
    - matplotlib-base

test:
  imports:
    - rfpimp

about:
  home: https://github.com/parrt/random-forest-importances
  license: MIT
  license_family: MIT
  summary: 'Code to compute permutation and drop-column importances in Python scikit-learn random forests'

extra:
  recipe-maintainers:
    - ericmjl
